server:
  servlet:
    context-path: /mall-server
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    name: spring_boot_mybatis
    url: jdbc:mysql://gz-cdb-omnfkg4j.sql.tencentcdb.com:62135/gs?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: gs123456
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid 数据源
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host:
#    host: 127.0.0.1
#    port: 6379
#    password:


#mybatis:
#  mapper-locations: classpath:mapper/*/*.xml
#  type-aliases-package: com.dd.server.modules.*.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.dd.server.modules.*.entity
